# Generated by Django 3.2 on 2021-11-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Live', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newresource',
            name='resource',
            field=models.CharField(choices=[('sensor', 'sensor'), ('actuator', 'actuator')], default='sensor', max_length=8),
        ),
    ]
