# Generated by Django 3.2 on 2021-11-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Live', '0002_newresource_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='newresource',
            name='resource_input',
            field=models.CharField(choices=[('sensor', 'sensor(no input)'), ('switch', 'switch'), ('slider', 'slider')], default='sensor', max_length=8),
        ),
    ]
