# Generated by Django 3.2 on 2021-11-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Live', '0003_newresource_resource_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newresource',
            name='resource',
            field=models.CharField(choices=[('sensor', 'sensor'), ('actuator', 'actuator'), ('bot', 'bot')], default='sensor', max_length=8),
        ),
        migrations.AlterField(
            model_name='newresource',
            name='resource_input',
            field=models.CharField(choices=[('sensor', 'sensor(no input)'), ('switch', 'switch')], default='sensor', max_length=8),
        ),
    ]
